# Generated by Django 5.1.1 on 2024-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Store', models.IntegerField(default=1)),
                ('DayOfWeek', models.IntegerField(default=1)),
                ('Date', models.DateField()),
                ('Open', models.IntegerField(default=1)),
                ('Promo', models.IntegerField(choices=[(0, 'zero: 0'), (1, 'One: 1')])),
                ('StateHoliday', models.CharField(choices=[('0', 'Zero: 0'), ('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('SchoolHoliday', models.IntegerField(choices=[(0, 'zero: 0'), (1, 'One: 1')])),
                ('StoreType', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1)),
                ('Assortment', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C')], max_length=1)),
                ('CompetitionDistance', models.FloatField(default=0)),
                ('CompetitionOpenSinceMonth', models.IntegerField(default=0)),
                ('CompetitionOpenSinceYear', models.IntegerField(default=0)),
                ('Promo2', models.IntegerField(choices=[(0, 'zero: 0'), (1, 'One: 1')])),
                ('Promo2SinceWeek', models.IntegerField(default=0)),
                ('Promo2SinceYear', models.IntegerField(default=0)),
                ('PromoInterval', models.CharField(choices=[('Jan,Apr,Jul,Oct', 'Jan,Apr,Jul,Oct'), ('Feb,May,Aug,Nov', 'Feb,May,Aug,Nov'), ('Mar,Jun,Sept,Dec', 'Mar,Jun,Sept,Dec')], max_length=100)),
            ],
        ),
    ]
